name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows,     os: windows-latest }
        - { name: Linux,   os: ubuntu-latest }
        config:
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev libharfbuzz-dev libmbedtls-dev libssh2-1-dev

    - name: Checkout
      uses: actions/checkout@v7

    - name: Configure
      run: cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}

    - name: Build
      run: cmake --build build --config Release

    - name: Rename Binary
      run: |
        if [ -f "build/bin/tdt" ]; then
          mv build/bin/tdt build/bin/tdt-${{ matrix.platform.name }}-${{ matrix.config.name }}
        fi
        if [ -f "build/bin/Release/tdt.exe" ]; then
          mv build/bin/Release/tdt.exe build/bin/Release/tdt-${{ matrix.platform.name }}-${{ matrix.config.name }}.exe
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: tdt-${{ matrix.platform.name }}-${{ matrix.config.name }}
        if-no-files-found: ignore
        path: |
          build/bin/tdt-*
          build/bin/Release/tdt-*
        retention-days: 14
